// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZCnMnL_rYc5k0cWymjV-vXG5oTAKvHm4',
    appId: '1:286294435048:web:a7700dc4934472d3bf555d',
    messagingSenderId: '286294435048',
    projectId: 'chatapp-9dbf4',
    authDomain: 'chatapp-9dbf4.firebaseapp.com',
    storageBucket: 'chatapp-9dbf4.appspot.com',
    measurementId: 'G-2YZW4T9KMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuiShO_9Ht7p9NL6zNST5-daLONWtM8lI',
    appId: '1:286294435048:android:5f636be78a6a2c20bf555d',
    messagingSenderId: '286294435048',
    projectId: 'chatapp-9dbf4',
    storageBucket: 'chatapp-9dbf4.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZCnMnL_rYc5k0cWymjV-vXG5oTAKvHm4',
    appId: '1:286294435048:web:f6e9ec1a7a875c2fbf555d',
    messagingSenderId: '286294435048',
    projectId: 'chatapp-9dbf4',
    authDomain: 'chatapp-9dbf4.firebaseapp.com',
    storageBucket: 'chatapp-9dbf4.appspot.com',
    measurementId: 'G-S4M43HQD0Y',
  );
}
